# version: "3.3"
version: "3.9"

services:
  db:
    container_name: pgsq
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # test_db:
  #   container_name: pgsq_tests
  #   image: postgres:15
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_TEST_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_TEST_DB}
  #   ports:
  #     - "5433:5432"  

  web:
    build: .
    container_name: api_restful
    command: sh -c "alembic upgrade head && uvicorn api_restful.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      # - test_db
    environment:
      - DATABASE_URL=${DATABASE_URL}

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - db
volumes:
  pgdata:
