"""add username unique in SystemUser model, migration

Revision ID: 07bfe98fabbe
Revises: db4a1e9e13cb
Create Date: 2025-04-20 14:53:17.719439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07bfe98fabbe'
down_revision: Union[str, None] = 'db4a1e9e13cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'system_users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'system_users', type_='unique')
    # ### end Alembic commands ###
