"""Created Orders model and migrations

Revision ID: 2e2b6b2cb156
Revises: e14df46e3b4a
Create Date: 2025-04-19 21:36:44.568094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e2b6b2cb156'
down_revision: Union[str, None] = 'e14df46e3b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('created', 'processing', 'completed', 'canceled', name='orderstatus'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('order_products',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id', 'product_id')
    )
    # op.alter_column('clients', 'gender',
    #            existing_type=sa.VARCHAR(length=1),
    #            type_=sa.Enum('female', 'male', 'other', name='genderstatus'),
    #            existing_nullable=True)
    op.drop_column('clients', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('clients', 'gender',
    #            existing_type=sa.Enum('female', 'male', 'other', name='genderstatus'),
    #            type_=sa.VARCHAR(length=1),
    #            existing_nullable=True)
    op.add_column('clients', sa.Column('gender', sa.String(length=1), nullable=True))
    op.drop_table('order_products')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
