"""empty message

Revision ID: 4325ed706c8d
Revises: 3de64dc5d4ac
Create Date: 2025-04-21 03:43:20.718857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4325ed706c8d'
down_revision: Union[str, None] = '3de64dc5d4ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders_products', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders_products', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('orders_products_order_id_fkey', 'orders_products', type_='foreignkey')
    op.drop_constraint('orders_products_product_id_fkey', 'orders_products', type_='foreignkey')
    op.create_foreign_key(None, 'orders_products', 'orders', ['order_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orders_products', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders_products', type_='foreignkey')
    op.drop_constraint(None, 'orders_products', type_='foreignkey')
    op.create_foreign_key('orders_products_product_id_fkey', 'orders_products', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('orders_products_order_id_fkey', 'orders_products', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.alter_column('orders_products', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders_products', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
