"""add genderstatus enum

Revision ID: 93193ce54650
Revises: 2e2b6b2cb156
Create Date: 2025-04-19 21:50:31.431506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93193ce54650'
down_revision: Union[str, None] = '2e2b6b2cb156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    gender_enum = sa.Enum('female', 'male', 'other', name='genderstatus')
    gender_enum.create(op.get_bind())
    op.add_column('clients', sa.Column('gender', sa.Enum('female', 'male', 'other', name='genderstatus')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'gender')
    gender_enum = sa.Enum('female', 'male', 'other', name='genderstatus')
    gender_enum.drop(op.get_bind())
    # ### end Alembic commands ###
