"""add product_quantity in order_products table associated

Revision ID: db4a1e9e13cb
Revises: 93193ce54650
Create Date: 2025-04-19 22:05:51.407181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db4a1e9e13cb'
down_revision: Union[str, None] = '93193ce54650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_products', sa.Column('product_quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_products', 'product_quantity')
    # ### end Alembic commands ###
