name: Run Tests on Push with Docker Compose

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Rodar pytest
        env:
          DATABASE_URL: postgresql://database_0os9_user:49kwG0vFul3xrdsxStG4dxUY43ijV1IZ@dpg-d038u93uibrs7385n6cg-a/database_0os9
        run: |
          pytest
